# **Python Tutorial, NumPy**



This is an introduction to Numpy
It uses a tutorial from FreeCodeCamp.org, at: https://www.youtube.com/watch?v=QUT1VHiLmmI

In [55]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


The Basics

In [ ]:
b = np.array([1, 2, 3])
print(b)

[1 2 3]


In [ ]:
a = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(a)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
print(a.ndim)
print(b.shape)
print(a.dtype)
print(a.itemsize)

2
(3,)
float64
8


In [ ]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r,c]
print(c[1,5])
print(c[1,-1])

#Get a specific row
print(c[0,:])

#Get a specific column
print(c[:,1])

13
14
[1 2 3 4 5 6 7]
[2 9]


In [ ]:
#Show [startindex : endindex : stepsize]
#Show row 0, from column 1 to 6, every two elements
print(c[0,1:6:2])

[2 4 6]


In [ ]:
#Modify a column and put new values into it
c[:,2] = [1,2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [ ]:
# 3D arrays
d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print (d)

#Replace one dimension
d[:,1,:] = [[9,9], [10,10]]
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [10 10]]]


**Initializing Different Types of Arrays**

In [ ]:
x1 = np.zeros((2,3))
print(x1)

x2 = np.ones((4,2,2), dtype='int32')
print(x2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [ ]:
#Create an array full of one number
x3 = np.full((2,2), 99)
print(x3)

#Creatr an array using the shape of another array
x4 = np.full_like(a, 33)
print(x4)

[[99 99]
 [99 99]]
[[33. 33. 33.]
 [33. 33. 33.]]


In [ ]:
#Create random arrays
x5 = np.random.rand(4,2)
print(x5)

[[0.15001257 0.09868098]
 [0.8214546  0.07777526]
 [0.92036525 0.31371088]
 [0.36921967 0.65149271]]


In [ ]:
#Random Integer values
x6 = np.random.randint(7, size=(3,3))
print(x6)

x7 = np.random.randint(-4, 8, size=(3,3))
print(x7)

x8 = np.identity(5)
print(x8)

[[1 1 2]
 [6 3 1]
 [1 2 1]]
[[ 4  2 -2]
 [ 2  4 -1]
 [ 6  1  0]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]])#One dimensional array
#It repeats arr one row at a time
r1 = np.repeat(arr, 3, axis=0)
print(r1)

#It repeats arr one value at a time
r2 = np.repeat(arr, 3, axis=1)
print(r2)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
output = np.ones((5,5))
print (output)

z = np.zeros((3,3))
z[1,1] = 9
print (z)

#Desde la fila 1 hasta el final y desde col 1 hasta el final
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Rules of copying arrays

In [ ]:
#Be careful when copying arrays

a = np.array([1, 2, 3])
#We are making a the same as b
b = a
# We are copying the contents
c = a.copy()
b[0] = 100
print(a)
print (c)

[100   2   3]
[1 2 3]


**Array Mathematics** 

In [ ]:
a = np.array([1, 2, 3])
print(a/2)
b = np.array([1,0,1])
print(a+b)

[0.5 1.  1.5]
[2 2 4]


In [ ]:
a = ([1, 0, 1])
print(np.cos(a))

[0.54030231 1.         0.54030231]


**Linear Algebra**

In [ ]:
a = np.ones((2,3))

b = np.full((3,2), 2)
print(a)
print(b)

#Matrix multiplication
c = np.matmul(a, b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
#Other things you could do:
#Determinant, Trace, Singular Vector Decomposition, Eigenvalues, Matrix Norm
#Inverse, etc
c = np.identity(3)
d = np.linalg.det(c)
print(d)

1.0


**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])

print(np.min(stats))

print(np.max(stats))

#Calculate the maximum for each column
print(np.max(stats, axis=0))

#Calculate the maximum value for each row
print(np.max(stats, axis=1))

1
6
[4 5 6]
[3 6]


**Reorganizing Arrays**

In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
after = before.reshape((8,1))
print (after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
#Vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.vstack([v1, v2, v1, v2])
print(v3)

#Horizontally stacking

v4 = np.ones((2,4))
v5 = np.zeros((2,2))
v6 = np.hstack((v4, v5))
print(v6)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


**Miscellaneous**

In [58]:
filedata = np.genfromtxt('/content/drive/My Drive/Colab Notebooks/Python Tutorials/data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)


[[ 1  3  5  8 13 21 34 55 89]
 [ 1  3  5  8 13 21 34 55 89]
 [ 1  3  5  8 13 21 34 55 89]
 [ 1  3  5  8 13 21 34 55 89]]


In [60]:
#bOOLEAN mASKING AND Advanced Indexing

#Print true or false in array form for each value of the loaded data
print(filedata > 50)

print((filedata > 10) & (filedata < 30))

[[False False False False False False False  True  True]
 [False False False False False False False  True  True]
 [False False False False False False False  True  True]
 [False False False False False False False  True  True]]
[[False False False False  True  True False False False]
 [False False False False  True  True False False False]
 [False False False False  True  True False False False]
 [False False False False  True  True False False False]]
