## **Random Numbers**

In [13]:
import random

#Pseudo-random

a = random.random()
print(a)

b = random.uniform(1, 10)
print(b)

c = random.randint(1, 10)
d = random.randrange(1, 10) # the top range is not included
e = random.normalvariate(0, 1) # Random value from a Normal distribution
print(c)

mylist = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
a = random.choice(mylist)
b = random.sample(mylist, 3)
print(a)
print(b)

random.shuffle(mylist)
print(mylist)

0.9911813705668003
7.371931926316638
7
H
['L', 'I', 'M']
['L', 'N', 'Q', 'H', 'D', 'V', 'B', 'P', 'X', 'E', 'K', 'F', 'S', 'M', 'O', 'W', 'R', 'I', 'J', 'Y', 'C', 'Z', 'T', 'U', 'G', 'A']


In [16]:

#You can reproduce your numbers by using the same seed
random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1


**Secrets**

Used for passwords, security tokens, etc.

In [21]:

import secrets

a = secrets.randbelow(10)
print(a)

# It will use 4 bits (1111 means the max number is 15)
b = secrets.randbits(4)
print(b)

mylist = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
c = secrets.choice(mylist)
print(c)

2
4
W


**Using NumPy**

In [26]:
import numpy as np
a = np.random.rand(3)
print(a)

# From 0 to 9, a total of 3 elements will be generated
b = np.random.randint(0, 10, 3)
print (b)

# From 0 to 9, an array of [3,4] elements will be generated
b = np.random.randint(0, 10, (3, 4))
print (b)

np.random.shuffle(b)
print(b)

#This is a different seed function than the previous one
np.random.seed(1)
print(np.random.rand(3,3))

np.random.seed(1)
print(np.random.rand(3,3))


[0.58650363 0.41900621 0.78828814]
[3 7 3]
[[7 7 8 3]
 [8 9 0 0]
 [6 6 5 2]]
[[8 9 0 0]
 [7 7 8 3]
 [6 6 5 2]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
